name: Deploy to Play Store

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdkVersion: '31'

      - name: Build release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.example.app
          bundleFile: android/app/build/outputs/bundle/release/app-release.aab
          track: alpha
          releaseName: v1.0.0-alpha.1
          releaseNotes: This is the first alpha release.
